### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by Upcreat** [uuup123/FC-HAT#1]
Hello author, this is an excellent project. May I know if the 'data' link in your project has expired? If so, could you please provide a new link? Also, I noticed that there are no corresponding values for some parameters in the 'config.yaml' file. Could you please provide them as well? Thank you.

**Comment by benluejue** [comment]
Hello，sir, have you resolved this issue? I only obtained only a partial labels.csv file.

**Comment by benluejue** [comment]
Hi,sir,have you resolved this issue?I have obtained only a partial labels.csv file.

**Comment by Upcreat** [comment]
I didn't get it either

**Comment by uuup123** [comment]
Sorry, this is a large file, and github only supports files smaller than 25MB, so I can only upload the data to the network disk and share the data through links. 

Since there was a problem with Alibaba Cloud Disk, I re-uploaded the data to Baidu Cloud Disk. 

The link is: https://pan.baidu.com/s/1bQzSLGhTp0Ud2oNSFex7Lw?pwd=t4j8 
and the code is: t4j8

**Comment by Upcreat** [comment]
Thanks for the author's reply.

**Comment by benluejue** [comment]
Thanks for the author's reply . Thank you very much!!!!!

**Comment by uuup123** [comment]
> Hello author, this is an excellent project. May I know if the 'data' link in your project has expired? If so, could you please provide a new link? Also, I noticed that there are no corresponding values for some parameters in the 'config.yaml' file. Could you please provide them as well? Thank you.

Sorry, this is a large file, and github only supports files smaller than 25MB, so I can only upload the data to the network disk and share the data through links. 

Since there was a problem with Alibaba Cloud Disk, I re-uploaded the data to Baidu Cloud Disk. 

The link is: https://pan.baidu.com/s/1bQzSLGhTp0Ud2oNSFex7Lw?pwd=t4j8 
and the code is: t4j8
